name: Generate Snake

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"

jobs:
  snake:
    runs-on: ubuntu-latest
    steps:
      - uses: Platane/snk/svg-only@v3
        with:
          github_user_name: Prath-Digital
          outputs: dist/snake.svg
      - uses: actions/upload-artifact@v3
        with:
          name: snake
          path: dist/snake.svg
